package markus.wieland.pushygame.engine.level;

import com.google.gson.annotations.SerializedName;

public enum EntityType implements Tag {
    @SerializedName("tree") TREE,
    @SerializedName("box") BOX,
    @SerializedName("pushy") PUSHY,
    @SerializedName("finish") FINISH,
    @SerializedName("stone") STONE,
    @SerializedName("no_entity") NO_ENTITY,
    @SerializedName("seastar") SEA_STAR,
    @SerializedName("seed") SEED,
    @SerializedName("bottle") BOTTLE,
    @SerializedName("statue_red") STATUE_RED,
    @SerializedName("statue_blue") STATUE_BLUE,
    @SerializedName("statue_green") STATUE_GREEN,
    @SerializedName("bomb") BOMB,
    @SerializedName("crab_baby") CRAB,
    @SerializedName("crab_mother") CRAB_MOTHER,
    @SerializedName("slingshot") SLING_SHOT,
    @SerializedName("shot") SHOT,
    @SerializedName("coconut") COCONUT,
    @SerializedName("leaf_down") LEAF_DOWN,
    @SerializedName("leaf_up") LEAF_UP,
    @SerializedName("leaf_left") LEAF_LEFT,
    @SerializedName("leaf_right") LEAF_RIGHT,
    @SerializedName("pirat") PIRATE,
    @SerializedName("pirat_hut") PIRATE_HUT,
    @SerializedName("chest") CHEST,
    @SerializedName("coin") COIN,
    @SerializedName("key") KEY,
    @SerializedName("tower") TOWER,
    @SerializedName("pearl") PEARL,
    @SerializedName("shell") SHELL,
    @SerializedName("shell_open_with_pearl") SHELL_OPEN_WITH_PEARL,
    @SerializedName("count_one") COUNT_ONE,
    @SerializedName("count_two") COUNT_TWO,
    @SerializedName("count_three") COUNT_THREE,
    @SerializedName("count_four") COUNT_FOUR,
    @SerializedName("count_five") COUNT_FIVE,
    @SerializedName("flower") FLOWER_YELLOW,
    @SerializedName("flower_red") FLOWER_RED,
    @SerializedName("shell_1") SHELL_1,
    @SerializedName("shell_2") SHELL_2,
    @SerializedName("shell_3") SHELL_3,
    @SerializedName("octopus") OCTOPUS,
    @SerializedName("barrel") BARREL,
    @SerializedName("leaf_changer_east") LEAF_CHANGER_EAST,
    @SerializedName("leaf_changer_west") LEAF_CHANGER_WEST,
    @SerializedName("leaf_changer_north") LEAF_CHANGER_NORTH,
    @SerializedName("leaf_changer_south") LEAF_CHANGER_SOUTH,

}
